# cfg/defaults.py

YOLO_MAX_SIDE = 1280

TEXT_MODE = "qt"
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720

SLOTS = 64
LOCAL_Q_MAX = 60
PRINT_EVERY = 120
USE_HWACCEL = False

LIMIT_DECODE_SPEED = True


STRICT_ANALYTICS_MODE = True

WAIT_WHEN_QUEUES_FULL = True
BACKPRESSURE_HWM = max(1, SLOTS - 4)
BATCH_SIZE = 8
MAX_BATCH_DELAY_MS = 40
